// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3ufpHIaowfOQxOjjGW71ITyWtihehQ',
    appId: '1:157697537690:android:48813ac73bc022bb815123',
    messagingSenderId: '157697537690',
    projectId: 'tailor-d2675',
    databaseURL: 'https://tailor-d2675-default-rtdb.firebaseio.com',
    storageBucket: 'tailor-d2675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjVZOMhZjSsB24yW5220azGd0wzv6x_I',
    appId: '1:157697537690:ios:f053f7cf2427ed9f815123',
    messagingSenderId: '157697537690',
    projectId: 'tailor-d2675',
    databaseURL: 'https://tailor-d2675-default-rtdb.firebaseio.com',
    storageBucket: 'tailor-d2675.appspot.com',
    iosClientId: '157697537690-8t2rl4mpk8um94c43vafbm6nn7p9do01.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailor',
  );
}
